name: "Automerge PR"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: automerge
        if: ${{ contains(github.event.pull_request.labels.*.name, 'automerge') }}
        name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          MERGE_LABELS: "automerge"
          MERGE_METHOD_LABEL_REQUIRED: "false"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_METHOD: "squash"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"

      - name: feedback
        if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
        run: echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
