name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - 'pytorch_optimizer/__init__.py'
      - 'pytorch_optimizer/optimizer/__init__.py'
      - 'pytorch_optimizer/lr_scheduler/__init__.py'
      - 'pytorch_optimizer/loss/__init__.py'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Update documentation files
        run: python scripts/update_docs.py

      - name: Commit updated documentation
        uses: stefanzweifel/git-auto-commit-action@v6
        id: auto-commit-action
        with:
          commit_message: "[skip ci] docs: update documentation"
          file_pattern: "docs/optimizer.md docs/lr_scheduler.md docs/loss.md"
          commit_user_name: "pytorch_optimizer-actions[bot]"
          commit_user_email: "pytorch_optimizer-actions[bot]@users.noreply.github.com"
          push_options: "--force"
